/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.*;

public class AppTest {
    //test case to check for when my application is able to successfully read a json file and return a string of the files content
    @Test
    public void testReadFileHappy() {
        App classUnderTest = new App();
        String path = "src/main/resources/recentquotes.json";
        assertNotNull("this method call should return a string", classUnderTest.readFile(path));
    }

    //test case to check for when my applications error checker works for an invalid path
   @Test
    public void testReadFileFail() {
        App classUnderTest = new App();
        String path = "someRandomPath";
        String expectedOutput = "";
        assertEquals("This should return an empty string if it fails",expectedOutput, classUnderTest.readFile(path));
    }

    //test case to check for when my application is able to convert a json string into an array of quotes
    @Test
    public void testConvertToQuoteClass() {
        App classUnderTest = new App();
        String path = "src/main/resources/recentquotes.json";
        String jsonString = classUnderTest.readFile(path);
        assertNotNull("this method call should return a string", classUnderTest.convertToQuoteClass(jsonString));
    }

    //test to check for when my application is able to successfully generate a random quote
    @Test
    public void testGenerateRandomQuote() {
        App classUnderTest = new App();
        String path = "src/main/resources/recentquotes.json";
        String jsonString = classUnderTest.readFile(path);
        Quotes[] quoteArr = classUnderTest.convertToQuoteClass(jsonString);
        assertNotNull("this method call should return a string", classUnderTest.generateRandomQuote(quoteArr));
    }


}
