/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Random;
import java.util.Scanner;

public class App {

    //function to read a file from a file path and parse that files content into a string
    public String readFile(String path){
        try {
            Scanner sc = new Scanner(new File(path));
            StringBuilder jsonString = new StringBuilder();
            while(sc.hasNextLine()){
                jsonString.append(sc.nextLine());
            }
            return jsonString.toString();
        } catch (FileNotFoundException e){
            System.out.println(("File not found"));
            System.out.println(e);
            return "";
        }
    }
//function to convert a json string into an array of quote instances
    public static Quotes[] convertToQuoteClass(String jsonString){
        Gson gson = new Gson();
        Quotes[] quotesArr = gson.fromJson(jsonString, Quotes[].class );
        return quotesArr;
    }
//function to generate a random quote from the list of quote instances in the array
    public static Quotes generateRandomQuote(Quotes[] quote){
        Random rand = new Random();
        int randomNum = rand.nextInt(quote.length);
        return quote[randomNum];
    }
}
